server:
  port: 8001
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/aili/*/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.72.32:3306/guli?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: 123456789E
    hikari:
#      read-only: false
#      connection-test-query: SELECT 1
#      connection-timeout: 60000000
#      idle-timeout: 500000
      max-lifetime: 30000
  #      maximum-pool-size: 12
#      minimum-idle: 10
#      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT
#    Nacos服务注册
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 47.101.72.32
    database: 0
    password: 123456e
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
#nacos服务地址

#    配置日志
#logging:
#  level: {
#           root: warn
#  }
#开启器熔断机制
feign:
  hystrix:
    enabled: true
#默认超时时间 1000ms



